# Generated by Django 6.0.7 on 2026-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], db_index=True, default='PUBLISHED', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], db_index=True, default='PUBLISHED', max_length=15),
        ),
    ]
