# Generated by Django 6.0.7 on 2026-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, default='BIS 916 Hallmarked & Certified', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='e.g. IND-NK-001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. Bridal, Popular, New Arrival', max_length=255, null=True),
        ),
    ]
