# Generated by Django 6.0.7 on 2026-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_certification_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_flags',
            field=models.CharField(blank=True, help_text='Comma-separated custom badges, e.g. Featured, Bestseller, Trending', max_length=255, null=True),
        ),
    ]
