# Generated by Django 6.0.7 on 2026-08-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_custom_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='banners/')),
                ('title_line_1', models.CharField(help_text='e.g. Timeless Beauty.', max_length=150)),
                ('title_line_2', models.CharField(help_text='e.g. Crafted with', max_length=150)),
                ('gold_word', models.CharField(help_text='e.g. Tradition.', max_length=100)),
                ('description', models.TextField(help_text='Banner description paragraph.')),
                ('order', models.IntegerField(default=0, help_text='Slide display order.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle banner visibility.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
